### ISSUE TITLE
Shell theme does not works correctly while using gnome classic shell

### ISSUE THREAD

**Issue by subhammridha** [lassekongo83/plano-theme#28]
Hello,

I very much like your theme, but the problem is I also happen to use the gnome 3 classic shell. 

In it, the window decoration (gtk theme) works fine, but when I apply the shell theme it does not looks good. I have added the following screenshots in order to better explain the problem.

![screenshot from 2018-04-27 19-36-09](https://user-images.githubusercontent.com/16416796/39367270-c76dc2a4-4a25-11e8-8e1f-57edf841e8e3.png)
![screenshot from 2018-04-27 21-16-35](https://user-images.githubusercontent.com/16416796/39371867-6ca6109e-4a32-11e8-968f-71f6d88596b7.png)

As can be seen from the images, the top and bottom panels do not render properly and looks ugly.

Therefore, if possible, please rectify this problem.
If this is some minor glitch, it would really help if I can know the steps on how to correct it myself.

**Comment by lassekongo83** [comment]
There are not many options left to style gnome classic from what I understand. The only thing I could style was the panel, not the buttons. However, you'll have to add this one yourself as a global fix is not possible. It would break the default shell theme.

Open `gnome-shell/gnome-shell-sass/_common.scss`. Search for `#panel`. Change the background-color to `#ebeced`. Below it add:

    background-gradient-direction: vertical;
    background-gradient-end: #ebeced;

Save. Open a terminal and install `sassc` if you haven't already. Run the `parse-sass.sh` file. Press CTRL+F2 and type `rt`. The gradient should be gone.

MATE would be a better choice instead of gnome-classic. You can use a similar setup there.

**Comment by subhammridha** [comment]
Thanks a lot for the advice. The gradient in the panel indeed was gone. But the texts in the panel are now is illegible as they are in white.

I have tried MATE in the past but have faced some page tearing issues while scrolling and playing videos. Therefore, I came back to gnome. Also the new search feature in Applications is indispensable in gnome 3.

**Comment by lassekongo83** [comment]
Search for `.panel-button` and change `color: $fg_color;` to `color: black;`. There may also be some additional color values below that need to be changed as well.

You could also make the panel dark. Set `background-color` and `background-gradient-end` to `$bg_color` instead. However, the buttons in the bottom panel will still be bright. I haven't found any way to style them.

**Comment by subhammridha** [comment]
That did it.
I also had to change the hover colour though.

Thanks again for your help.
