### ISSUE TITLE
Overall problems with new Ubuntu 20.04 LTS release.

### ISSUE THREAD

**Issue by PranavBhattarai** [lassekongo83/plano-theme#51]
1. A black-themed notification where details are hidden. Here details are hidden. Details like, "Trent Reznor and Atticus Ross - In Motion - VLC media player". This text color should have been white instead of invisible black. Because of this, almost all notifications are invisible.

![Screenshot from 2020-05-11 21-01-38](https://user-images.githubusercontent.com/32763112/81579545-0681c200-93cc-11ea-806b-d1d44974d08b.png)

2. The name of the software should have been in black color instead of invisible white in the notification panel.
![Screenshot from 2020-05-11 21-02-11](https://user-images.githubusercontent.com/32763112/81579550-07b2ef00-93cc-11ea-9ea3-2c629ce4abf6.png)
3. And the name of Month (**May**) should have been black instead of white.

Bonus problem:
If problem 2 is somehow be fixed, you should know the touching the will look like this:
![Screenshot from 2020-05-11 21-22-05](https://user-images.githubusercontent.com/32763112/81580758-92e0b480-93cd-11ea-8be6-991f525975de.png)

On the other hand with [Ubuntu's Yaru theme](https://github.com/ubuntu/yaru), we have this:

![Screenshot from 2020-05-11 21-25-04](https://user-images.githubusercontent.com/32763112/81581246-30d47f00-93ce-11ea-9511-4bcdff612864.png)
![Screenshot from 2020-05-11 21-25-13](https://user-images.githubusercontent.com/32763112/81581248-329e4280-93ce-11ea-9047-130d0b59921c.png)

**GNOME**: **3.36.1**

**Comment by th3bucch** [comment]
At the issue rased by  @PranavBhattarai i'll add the fact that Ubuntu Software Manager has no theme at all, resulting in a transparent backgound and no stiles for buttons, menus and whatnot.
Same behavior installing .deb packages via GUI  because they're handled by the same software.

Here a screen with plano theme (you can clearly see my desktop background)
![US_plano](https://user-images.githubusercontent.com/57603626/82652438-e947c180-9c1d-11ea-8655-74e66e5c14d8.png)

And the same window with yaru theme
![US_yaru](https://user-images.githubusercontent.com/57603626/82652471-f5338380-9c1d-11ea-8376-1b81fbc10490.png).

**Comment by PranavBhattarai** [comment]
@th3bucch 
I use **Yaru Dark** made by Canonical. 
There are three of them: Yaru, Yaru Dark, Yaru Light.
My **Software Center** looked like this:
![Screenshot from 2020-05-22 21-13-57](https://user-images.githubusercontent.com/32763112/82683917-81bb6180-9c71-11ea-93ae-127889ce4b05.png)
Transparency can create problem visibility issues, so I rather not tweak it so.
My panel looks like this if I drag my cursor toward menu bar or shortkey to revel:
![Screenshot from 2020-05-22 21-20-12](https://user-images.githubusercontent.com/32763112/82684388-381f4680-9c72-11ea-87ca-f4d9368b0546.png)

**Comment by lassekongo83** [comment]
@th3bucch: Where is the theme installed. In `/usr/share/themes/` or `~/.themes/` ?

**Comment by PranavBhattarai** [comment]
@th3bucch 
As per manual in [README.md](https://github.com/lassekongo83/plano-theme/blob/master/README.md), the theme is installed in `~/.themes/plano-theme` as u can see:
![image](https://user-images.githubusercontent.com/32763112/82725268-8298d580-9cfb-11ea-81ef-5e55fa2de9b5.png)

**Comment by th3bucch** [comment]
> @th3bucch: Where is the theme installed. In `/usr/share/themes/` or `~/.themes/` ?

Since I installed it via PPA when I was running Ubuntu 18.04 it is located in `/usr/share/themes` and i don't even know how to check what release version it is.

**Comment by lassekongo83** [comment]
@th3bucch: I'm not sure if this is possible, but try installing the theme in: `/var/lib/snapd/hostfs/usr/share/themes/`

Otherwise snap applications may not have the permission to read the theme. Bug on launchpad: `https://bugs.launchpad.net/snap-store/+bug/1867417`

Otherwise, keep the discussion about the snap-store here: https://github.com/lassekongo83/zuki-themes/issues/160 as this issue was about the gnome-shell theme.

**Comment by th3bucch** [comment]
@lassekongo83:
the solution you suggested isn't working. I also had to create `usr/share/themes/` folders inside `/var/lib/snapd/hostfs/`.

In the meantime I removed the theme from  `/usr/share/themes` and git-cloned again in `~/.themes/`. Now Ubuntu Software is fallbacking on Adwaita theme as mentioned on launchpad bug, and since I rarely use it it's ok to me. Let snap devs fix it when the time comes.

Thanks

**Comment by lassekongo83** [comment]
The issues with gnome-shell should be fixed with the new update. A new installation is required, as the theme is now built with meson. See the README.md file for more info.

**Comment by PranavBhattarai** [comment]
I fresh installed **plano-theme**, as u can see [here]( https://pastebin.com/nq67G1jQ).
But there is a huge problem.

Plano-theme was very cool/unique because it can display Time & Date _(basically everything that shows up in Menu bar)_ no matter whether if your **Panel** is transparent or not. If u see the below screenshot, u will know what I am trying to say.

![Screenshot from 2020-05-24 20-02-30](https://user-images.githubusercontent.com/32763112/82756664-4056bd80-9dfb-11ea-9675-ef0d3cdded06.png)
![Screenshot from 2020-05-24 20-00-10](https://user-images.githubusercontent.com/32763112/82756667-42b91780-9dfb-11ea-891d-7b6b518e6477.png)

This will create a huge problem when you are browsing the website white is NOT black in the background and if u are using software that is NOT dark themed. 

Now there is no difference in **Yaru-dark** shell VS Plano shell. This is no good.
Are you sure about these changes? Or, do you want me to create a new GitHub issue?

**Comment by lassekongo83** [comment]
Forgot to restore the dash-to-panel style.

**Comment by PranavBhattarai** [comment]
@lassekongo83 Thanks. Now it's back to normal (which is cool).
